name: Deploy Virginia Land Grant Atlas

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install tippecanoe
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsqlite3-dev zlib1g-dev
        git clone https://github.com/felt/tippecanoe.git
        cd tippecanoe
        make
        sudo make install
        
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Check if data file exists
      run: |
        if [ ! -f "data/raw/results_full_v2.csv" ]; then
          echo "⚠️  Data file data/raw/results_full_v2.csv not found"
          echo "Please add your data file to proceed with deployment"
          exit 1
        fi
        
    - name: Process data
      run: |
        python3 scripts/clean.py
        ./scripts/make_tiles.sh
        
    - name: Build frontend
      run: |
        cd frontend
        npm run build
        
    - name: Copy data to dist
      run: |
        mkdir -p frontend/dist/data
        cp data/grants.pmtiles frontend/dist/data/
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: virginia-atlas-dist
        path: frontend/dist/
        retention-days: 5
